### ISSUE TITLE
Evemon 4.2.0 crashes under Wine when adding an account

### ISSUE THREAD

**Issue by Strykar** [mgoeppner/evemon#43] opened 2022-04-17 10:54 UTC
Evemon (standalone version) starts fine, but crashes when I try to add an account.

OS: Arch Linux x64 kernel-5.17.3
Wine 7.6
Wine-Mono 7.2
```
EVEMon Version: 4.2.0.5032
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 6.1.7601.65536
Executable Path: Z:\home\strykar\Downloads\EVEMon-binaries-4.2.0\EVEMon\EVEMon.exe
System.NotImplementedException: The method or operation is not implemented.
  at EVEMon.Common.Service.SSOWebServerHttpListener..ctor () [0x0006e] in <8379b0648d954a339502bcabd4b22c0f>:0 
  at EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor () [0x00013] in <7f942678d4824c0dbfcec052be4a99fb>:0 
  at (wrapper remoting-invoke-with-check) EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor()
  at EVEMon.ApiCredentialsManagement.EsiKeysManagementWindow.addESIKeyMenu_Click (System.Object sender, System.EventArgs e) [0x00000] in <7f942678d4824c0dbfcec052be4a99fb>:0 
  at System.Windows.Forms.ToolStripItem.RaiseEvent (System.Object key, System.EventArgs e) [0x0001b] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.OnClick (System.EventArgs e) [0x00001] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripButton.OnClick (System.EventArgs e) [0x0001d] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.HandleClick (System.EventArgs e) [0x00051] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.HandleMouseUp (System.Windows.Forms.MouseEventArgs e) [0x000fd] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.FireEventInteractive (System.EventArgs e, System.Windows.Forms.ToolStripItemEventType met) [0x00053] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.FireEvent (System.EventArgs e, System.Windows.Forms.ToolStripItemEventType met) [0x00103] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripItem.FireEvent(System.EventArgs,System.Windows.Forms.ToolStripItemEventType)
  at System.Windows.Forms.ToolStrip.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x0007d] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001c3] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00043] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStrip.WndProc (System.Windows.Forms.Message& m) [0x00128] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.NativeWindow.Callback (System.Windows.Forms.Message& m) [0x00025] in <7eb7f98ebac24936922af35e6761d8be>:0 


Datafile report:
  eve-blueprints-en-US.xml.gzip (239KiB - 410280ee6121f561ac7f09354972ce38)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1011KiB - 957829e60281e4d412a0eef3020aeef9)
  eve-items-en-US.xml.gzip (3870KiB - a551e809290c88c634953b1c713daa1b)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (57KiB - 2b61fbc476da11385fc1ab2f058d91e8)
  eve-reprocessing-en-US.xml.gzip (112KiB - 8d9835c8b474942685888927396f4b7a)
  eve-skills-en-US.xml.gzip (26KiB - 0a84e91dcbece4b0d8d1e56f2619f5c5)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > EveMonClient.Initialize - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 01s > Settings.TryDeserializeFromFile - done
0d 0h 00m 01s > Settings.Import - begin
0d 0h 00m 01s > EveMonClient.OnSchedulerChanged
0d 0h 00m 01s > Settings.Import - done
0d 0h 00m 01s > EveMonClient.OnSettingsChanged
0d 0h 00m 01s > Main loop - start
0d 0h 00m 02s > EveMonClient.Run
0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 02s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 02s > Main window - loaded
0d 0h 00m 02s > Datafiles.Load - begin
0d 0h 00m 03s > TimeCheck.BeginCheckAsync
0d 0h 00m 03s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 03s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 05s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 14s > UpdateManager.OnCheckCompleted
0d 0h 00m 14s > UpdateManager.ScheduleCheck - in 12:00:00
0d 0h 00m 14s > Datafiles.Load - done
0d 0h 00m 14s > Settings.ImportData - begin
0d 0h 00m 14s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 14s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 14s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 14s > Settings.ImportData - done
0d 0h 00m 14s > EveMonClient.OnSettingsChanged

```
If this is indeed a duplicate of https://github.com/mgoeppner/evemon/issues/9 please close this.

**Comment by mgoeppner** [comment] 2022-04-18 20:12
@Strykar There are some native linux fixes here: https://github.com/mgoeppner/evemon/pull/41 -- There are some additional threading issues that are still preventing it from working properly under mono (UI thread is never updated) which wine uses which I haven't tracked down yet.

I haven't tried that branch with wine (only native mono), but if you would like to you can try the artifacts here: https://app.circleci.com/pipelines/github/mgoeppner/evemon/38/workflows/25b4ea45-46a4-4221-8930-63a30215d56b/jobs/35/artifacts

Be sure to reinstall 4.2.0 when you are finished, or updates may go a bit haywire.

Yes, this is a dupe of #9.

**Closed by mgoeppner** 2022-04-18 20:12 UTC

**Comment by mgoeppner** [comment] 2022-04-18 20:54
@Strykar I dug a bit more and fixed the remaining issue in the dispatcher that was broken on mono, and skipped some no flicker stuff which was breaking, so the core functionality should run under mono now.

Artifacts from the branch are here:
https://app.circleci.com/pipelines/github/mgoeppner/evemon/41/workflows/36f4907b-b4aa-46ce-9cdd-9034955a5720/jobs/38/artifacts
