### ISSUE TITLE
Application freezing when skillqueue planner is opened

### ISSUE THREAD

**Issue by SunStrider8420** [mgoeppner/evemon#63] opened 2023-10-26 00:14 UTC
Hello, 

Just today I noticed that when I run Evemon and open my skillqueue planner window, the entire app freezes.
If I quit out of the skillqueue planner window it goes back to normal.
Only change I can think of recently was a windows update that I applied.(Im still on Windows 10)

Please let me know what information you may need

**Comment by scuba-matt** [comment] 2023-10-27 08:08
I have this exact problem, which renders Evemon almost completely useless. I'm Windows 10, 64-bit version. I also notice that there appear to be a lot of error messages popping up at the bottom saying "Error logging into EVE SSO. If you changed your password, you must sign in again, using Add Character", but I definitely have not changed my passwords for those toons.

**Comment by NevarrTivianne** [comment] 2023-10-28 14:44
Yep, I also noticed this today for the first time.

A non-stable workaround seems to be closing the skill planner window (via the mouseover in your windows task bar), opening it again and **not** dragging anything and maybe closing and reopening it every time you change something, really annoying.

So I suppose it must have to do with external factors if this started this week for several people.

**Comment by SunStrider8420** [comment] 2023-10-28 15:05
> Yep, I also noticed this today for the first time.
> 
> A non-stable workaround seems to be closing the skill planner window (via the mouseover in your windows task bar), opening it again and **not** dragging anything and maybe closing and reopening it every time you change something, really annoying.
> 
> So I suppose it must have to do with external factors if this started this week for several people.

Hmm, that's odd.
For me, once I open my skill planner, I have a second before everything evemon-related freezes(Regardless of it I do anything or not). I have to close the skill planner window via Windows Task Manager. One other thing I noticed was Nord protection would start taking up tons of CPU usage when this happened, and Evemon would also jump from 3% or so to 15% CPU usage the moment I opened the Skill Planner.

**Comment by NevarrTivianne** [comment] 2023-10-29 12:25
You're right, I've restarted it countless times and tried different things.

Most often it's like this: Start it, up to 8% CPU and 300MB RAM, if I don't open anything it goes down to <1% CPU and 140MB RAM quickly (10-20s, I have ~20 chars in there and 9 are actively polled vi ESI).

Opening up one tab does nothing substantial but with a skill plan open it goes to 10% cpu, spikes to 600MB RAM, goes down to 500. Killing just that window, no CPU. That was with my "empty char" toon. Now after killing three of those, I can open either small or large skill plans on one of my main toons without problems.

So maybe it only does something when you open the skill planner the first few times? I'm confused.

**Comment by scuba-matt** [comment] 2023-11-02 20:45
An odd little thing I noticed is that the mouse cursor changes when it freezes, it shows the arrow+little notesheet icon (like the skill planner 'bars' icons that show what level of training you have in a skill). No matter what screen you are on, when it freezes, the cursor changes to that style for me, so maybe thats an indication of what it is trying to do.

Having seen the comments on the high CPU, I checked and mine is doign teh same thing, a significant increase in CPU/processor when it freezes - mine never unfreezes however, I have to force quit to get out of it.

**Comment by lunedis** [comment] 2023-11-05 14:50
same issue here.

**Comment by QuentinVnr01** [comment] 2023-11-05 20:08
same issue here

**Comment by Vartherion** [comment] 2023-11-06 22:48
Had the exact same issue.
File > Clear Cache seems to have resolved it for me.

**Comment by AnrDaemon** [comment] 2024-06-14 17:45
Thanks, cleaning cache helped. \o/

**Comment by mgoeppner** [comment] 2024-07-17 18:33
Resolved by 262f190f7828897dae77f14eb58f770255c488f1

This was being caused by some old evemarketer code still ticking, I never noticed it since I use fuzzworks -- this fix will be released in 5.x.x.

**Closed by mgoeppner** 2024-07-17 18:33 UTC
